sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
# Note: pypy3 fails at starting the bin/test script.
addons:
  apt:
    sources:
      - git-core
    packages:
      # git, bzr, subversion and mercurial are already installed by default,
      # we only need to install git-svn (but from the git-core PPA, as travis
      # uses that)
      - git-svn
    update: true

before_install:
  # Configure git and bazaar:
  - git config --global user.name "Temp user"
  - git config --global user.email "temp@example.com"
  - bzr whoami "Temp user <temp@example.com>"
  # Get the versions of the vcs programs, so we have this information in case
  # something goes wrong:
  - bzr --version
  - git --version
  - hg --version
  - svn --version
  - pip install -U setuptools
notifications:
  irc:
    channels: "irc.freenode.org#vanrees"
    on_success: change
env: HGUSER=temp
install:
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test -v
